version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "3G"
      PAPERMC_FLAGS: ""
    volumes:
      - "/home/pi/mcserver:/data:rw"
    ports:
      - "25565:25565/tcp"

    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true

    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    
  pluget:
    image: "bobrollenhagen/pluget:latest"
    restart: always
    container_name: "pluget"
    volumes:
      - "/home/pi/mcserver:/data/:rw"
    stdin_open: true
    tty: true
